version: '3.7'

services:

  react-ui:
    container_name: react-trelloclone
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 443:443
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://apitrelloclone.herokuapp.com

  nodejs-server:
    container_name: api-trelloclone
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
      - '.:/server'
      - '/server/node_modules'
    ports:
      - 3333:3333
    expose:
      - "3333"