name: "Deploy TrelloClone on Heroku"

on:
  push:
    branches:
      - master
    jobs:
      build:
        runs-on: ubuntu-latest
        env:
          working-directory: ./packages/backend
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        steps:
        - uses: actions/checkout@v1

        - name: Login to Heroku Container registry backend
          env: 
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            working-directory: ${{ env.working-directory }}
          run: heroku container:login 

        - name: Build and push backend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            working-directory: ${{ env.working-directory }}
          run: heroku container:push -a apitrelloclone web

        - name: Release backend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            working-directory: ${{ env.working-directory }}
          run: heroku container:release -a apitrelloclone web