name: "Deploy TrelloClone on Heroku"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Heroku Container registry backend
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          working-directory: ${{ secrets.BACKEND }}
        run: heroku container:login 

      - name: Build docker image
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          working-directory: ${{ secrets.BACKEND }}
        run: sudo docker build -t apitrelloclone .

      - name: Setup node.jobs
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          working-directory: ${{ secrets.BACKEND }}
        run: heroku container:login 

      - name: Push container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          working-directory: ${{ secrets.BACKEND }}
        run: heroku container:push -a apitrelloclone web
      
      - name: Release backend
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          working-directory: ${{ secrets.BACKEND }}
        run: heroku container:release -a apitrelloclone web